R 2.20.0 (#224)
* sormas: added demis integration

* docker env: make demis enabled false by default

* docker: add demis environment variable to sormas in docker compose

* Development (#163)

* Release Candidate 1.54.0

* fixed version of Keycloak zip

* Removed SJ_DEFAULT envs

* release 2.16.0-rc2

* Update Dockerfile

Co-authored-by: akm <amini@netzlink.com>
Co-authored-by: Adrian Sorge <aso@tpaso.nli>

* HCSA-590 fix behaviour of le-renew.sh

* Readded deleted lines from Dockerfile

* Remove duplicate demis setting of interface.demis.jndiName property

* Added createdefaultentities option
Fixed problems in keycloak compose file

* Add CREATE_DEFAULT_ENTITIES to all compose files

* Added CREATE_DEFAULT_ENTITIES to keycloak compose

* Fixed using wrong property name

* Prepare Release 1.59.0

* v2.20.0-rc1 (#213)

* sormas: added demis integration

* docker env: make demis enabled false by default

* docker: add demis environment variable to sormas in docker compose

* Development (#163)

* Release Candidate 1.54.0

* fixed version of Keycloak zip

* Removed SJ_DEFAULT envs

* release 2.16.0-rc2

* Update Dockerfile

Co-authored-by: akm <amini@netzlink.com>
Co-authored-by: Adrian Sorge <aso@tpaso.nli>

* Readded deleted lines from Dockerfile

* Remove duplicate demis setting of interface.demis.jndiName property

* Added createdefaultentities option
Fixed problems in keycloak compose file

* Add CREATE_DEFAULT_ENTITIES to all compose files

* Added CREATE_DEFAULT_ENTITIES to keycloak compose

* Fixed using wrong property name

* Prepare Release 1.59.0

Co-authored-by: Alex Vidrean <alexandru.vidrean@fxbits.io>
Co-authored-by: Adrian <adriansorge95@gmail.com>
Co-authored-by: akm <amini@netzlink.com>
Co-authored-by: Adrian Sorge <aso@tpaso.nli>

* Fixed wrong sed command

* changes made to pg_dump container to backup other databases than sormas and autit and additionally create release dumps (#215)

Co-authored-by: Tom Hutter <tom.hutter@unixum.de>

* Update start-server.sh

* rc2

* Add pg_dump fix to new release (#223)

* Get rid of debugging option

* keep last 10 backup files - if more - rotate

* Do not verify by grepping - test exit code instead

* Added exit code to pg_dump script - can be used when invoked as ansible script

* ZSTD as backup utility

* Revert "ZSTD as backup utility"

This reverts commit fc2023e92a0d834a144c2cd89bbec9db43622cbd.

Co-authored-by: Tomasz Nakonieczny <tomasz.nakonieczny@softgent.com>
Co-authored-by: Tom Hutter <TomHutter@users.noreply.github.com>

* Prepare release 2.20.0

Co-authored-by: Alex Vidrean <alexandru.vidrean@fxbits.io>
Co-authored-by: Adrian <adriansorge95@gmail.com>
Co-authored-by: akm <amini@netzlink.com>
Co-authored-by: Adrian Sorge <aso@tpaso.nli>
Co-authored-by: Frank Hauptmann <f.hauptmann@in2solutions.de>
Co-authored-by: tnako-sg <80451679+tnako-sg@users.noreply.github.com>
Co-authored-by: Tom Hutter <tom.hutter@unixum.de>
Co-authored-by: T-Hundt <72797817+T-Hundt@users.noreply.github.com>
Co-authored-by: Tomasz Nakonieczny <tomasz.nakonieczny@softgent.com>
Co-authored-by: Tom Hutter <TomHutter@users.noreply.github.com>

diff --git a/pg_dump/pg_dump b/pg_dump/pg_dump
--- a/pg_dump/pg_dump
+++ b/pg_dump/pg_dump
@@ -1,26 +1,45 @@
 #!/bin/sh
 
-DATE=$( date +%F-%T )
+# if parameter 1 is set use it as extension to the create file names"
+if [ -n "$1" ]; then
+  EXT=$1
+  DELETE=f
+else
+  EXT=$( date +%F-%T )
+  DELETE=t
+fi
+
 DUMP_PATH=/var/opt/db_dumps
 LOG=${DUMP_PATH}/pg_dump.log
-KEEP=${KEEP:-300}
 
-DBS="${DB_NAME} ${DB_NAME_AUDIT}"
+# Get a list of all databases and skip postgres and template databases
+DBS=$(psql -h ${DB_HOST} -U ${POSTGRES_USER} -l -t --field-separator=': ' -A -x | grep Name | awk '{ print $2 }' | grep -v -E 'postgres|template')
 
 for d in ${DBS};do
-  BAK="${DUMP_PATH}/$d.${DATE}.sql"
-  pg_dump -h ${DB_HOST} -U ${SORMAS_POSTGRES_USER} ${d} > ${BAK}
-  grep -q "PostgreSQL database dump complete" ${BAK}
-  if [ $? -eq 0 ];then
-    gzip ${BAK}
-    echo "Backup of ${d} to ${BAK}.gz completed." >> ${LOG}
-  else
-    rm ${BAK}
-    echo "Backup of ${d} to ${BAK} failed!!" >> ${LOG}
+  if [ "${DELETE}" == "t" ];then
+    echo "Deleting old dumps for ${d}" >> ${LOG}
+    # keep 1 day => delete all but the last 9 dumps
+    echo "$(ls -rt ${DUMP_PATH}/${d}.*.gz | head -n -9)" >> ${LOG}
+    ls -rt ${DUMP_PATH}/${d}.*.gz | head -n -9 | xargs -r rm
   fi
-done
 
-echo "Deleting old dumps" >> ${LOG}
-# keep 1 day => delete all but the last 10 dumps
-ls -rt ${DUMP_PATH}/sormas.20*.gz | head -n -10 | xargs -r rm
-ls -rt ${DUMP_PATH}/sormas_audit.20*.gz | head -n -10 | xargs -r rm
+  BAK="${DUMP_PATH}/$d.${EXT}.sql"
+  if [ -f "${BAK}.gz" ];then
+    echo "Backup of ${d} skipped. File ${BAK}.gz already exists!!" >> ${LOG}
+    continue
+  fi
+  pg_dump -h ${DB_HOST} -U ${POSTGRES_USER} ${d} > ${BAK}
+  if [ $? -eq 0 ];then
+    pigz ${BAK}
+    if [ $? -eq 0 ];then
+      # keep 9 + 1 = 10 backups - eventually
+      echo "Backup of ${d} to ${BAK}.gz completed." >> ${LOG}
+      continue
+    fi
+  fi
+  ## in case of error delete last backup
+  rm ${BAK}
+  echo "Backup of ${d} to ${BAK} failed!!" >> ${LOG}
+  exit 1;
+done
+exit 0;
