Updated to Sormas 1.61.1 (#249)
* Use new route for PIA rest API calls

* Set postgres to fixed version

* Add DCEXCLUDEARCHIVEDPERSONENTRIES property

* Remove if exists

* Add new env MAP_USECOUNTRYCENTER
Renamed env to DC_EXCLUDE_ARCHIVED_PERSON_ENTRIES

* Prepare RC 2.22.0-rc1

* Update start-server.sh

* Update start-server.sh

* ADD File Backup to PG_DUMP

* Revert "ADD File Backup to PG_DUMP"

This reverts commit e4d26e853000b634862d1baf308b8a7af2c5f3e5.

* Solution (2) for fixed postgres 10-alpine version (#246)

* Adding file-backup functionality (HCSA-818) (#244)

* MOD exit code for difference

* MOD set max backup to 10

* ADD configuration and default value

* MOD default file-backup-entry

* ADD quoting

* Commentary info when the hardcoded (by HCSA-1204) musl version can be abondoned.

* Switch back to old route because of bug

* Setting up Payara javamail-resource for email notifications (HCSA-1190). (#248)

* Define Payara javamail-resource with smtp-port and disabled smtp user/pass authentication based on .env props

* Email notification enablers

* Specify smpt-auth enabled in properties

* Pass notification env variables to docker-compose

* Default keeping status-quo values - email notification is off

* Appended notification env params to the rest of docker-compose*.yml files

* Readme description for Payara javamail notifications

* Updated to 1.61.1

Co-authored-by: akm <amini@netzlink.com>
Co-authored-by: Adrian <adriansorge95@gmail.com>
Co-authored-by: Nico Kahlert <nico.kahlert@outlook.de>
Co-authored-by: tnako-sg <80451679+tnako-sg@users.noreply.github.com>
Co-authored-by: Nico Kahlert <54364429+nk-designz@users.noreply.github.com>
Co-authored-by: Tomasz Nakonieczny <tomasz.nakonieczny@softgent.com>
Co-authored-by: JDR <dreier@netzlink.com>

diff --git a/pg_dump/pg_dump b/pg_dump/pg_dump
--- a/pg_dump/pg_dump
+++ b/pg_dump/pg_dump
@@ -46,4 +46,26 @@ for d in ${DBS};do
     exit 1;
   fi
 done
+
+# remove double quotations from variable
+BACKUP_FILES=$( echo $BACKUP_FILES | tr -d '"' )
+# Start Filebackup
+if [ -n "${BACKUP_FILES}" ]; then
+  FILE_BACKUP_TARGET=${DUMP_PATH}/files.${COMMON}${BAK_EXT}
+  echo "Backup of ${BACKUP_FILES} in ${BACKUP_PATH}" >> ${LOG}
+  cd ${BACKUP_PATH} && \
+  tar cf ${FILE_BACKUP_TARGET} -I 'zstd -T0 -${COMPRESSION_LEVEL}' ${BACKUP_FILES}
+  if [ $? -ge 1 ]; then
+    echo "Backup of ${BACKUP_FILES} in ${BACKUP_PATH} failed" >> ${LOG}
+    rm ${FILE_BACKUP_TARGET}
+    exit 42;
+  fi
+  if [ "${DELETE}" == "t" ];then
+    echo "Deleting old file backups" >> ${LOG}
+    # keep 1 day => delete all but the last 10 files - with .zst extention
+    echo "$(ls -rt ${DUMP_PATH}/files.*${BAK_EXT} | head -n -10)" >> ${LOG}
+    ls -rt ${DUMP_PATH}/files.*${BAK_EXT} | head -n -10 | xargs -r rm
+  fi
+fi
+
 exit 0;
